In [1]:
# Importações gerais
import pandas as pd

In [2]:
# Importando a base estática de jogadores da NBA
from nba_api.stats.static import players
# Pega uma lista de dicionários, cada um um jogador
nba_players = players.get_players()

In [3]:
###### TROCAR O NOME DO JOGADOR AQUI ##########
nome = 'Luka Doncic'
# Acha o dicionário correspondente ao jogador desejado
jogador = [player for player in nba_players
                   if player['full_name'] == nome][0]
jogador

{'id': 1629029,
 'full_name': 'Luka Doncic',
 'first_name': 'Luka',
 'last_name': 'Doncic',
 'is_active': True}

In [4]:
# Importando a API que acha os jogos
from nba_api.stats.endpoints import leaguegamefinder
# Procurando os jogos que o jogador participou
gamefinder = leaguegamefinder.LeagueGameFinder(player_id_nullable=jogador['id'])
jogos = gamefinder.get_data_frames()[0]
jogos.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22020,1610612742,DAL,Dallas Mavericks,0022000932,2021-04-27,DAL @ GSW,W,28,39,...,1.000,2,4,6,8,2,0,7,3,5.8
1,22020,1610612742,DAL,Dallas Mavericks,0022000926,2021-04-26,DAL @ SAC,L,38,24,...,0.667,0,8,8,8,0,0,4,2,-3.8
2,22020,1610612742,DAL,Dallas Mavericks,0022000908,2021-04-24,DAL vs. LAL,W,39,18,...,0.800,0,8,8,13,0,0,6,1,5.2
3,22020,1610612742,DAL,Dallas Mavericks,0022000897,2021-04-22,DAL vs. LAL,W,36,30,...,0.818,1,8,9,8,3,0,5,5,-0.8
4,22020,1610612742,DAL,Dallas Mavericks,0022000442,2021-04-21,DAL vs. DET,W,33,30,...,0.600,2,8,10,9,2,0,3,2,2.0

In [5]:
#A coluna de temporada tem um identificador numérico de tipo logo antes. Os ids de temporada regular começam com o número 2
jogos.groupby(jogos.SEASON_ID)[['GAME_ID']].count()

           GAME_ID
SEASON_ID
12018            4
12019            7
12020            3
22018           72
22019           61
22020           56
32018            1
32019            2
32020            1
42019            6

In [6]:
# Vamos fazer esse corte e manter apenas o ano
jogos = jogos[jogos['SEASON_ID'].str[0] == '2']
jogos['SEASON_ID'] = jogos['SEASON_ID'].str[-4:]

In [7]:
# Trocando o nome da coluna de temporada
colunas = list(jogos.columns)
colunas[0] = 'SEASON'
jogos.columns = colunas

In [8]:
# Criando uma coluna para dizer se o time jogou em casa
jogos['HOME'] = jogos['MATCHUP'].str[4:5] == 'v'

In [9]:
# Dimensões dos dados
jogos.shape

(189, 29)

In [10]:
# Tipos das colunas
jogos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 189 entries, 0 to 208
Data columns (total 29 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SEASON             189 non-null    object
 1   TEAM_ID            189 non-null    int64
 2   TEAM_ABBREVIATION  189 non-null    object
 3   TEAM_NAME          189 non-null    object
 4   GAME_ID            189 non-null    object
 5   GAME_DATE          189 non-null    object
 6   MATCHUP            189 non-null    object
 7   WL                 189 non-null    object
 8   MIN                189 non-null    int64
 9   PTS                189 non-null    int64
 10  FGM                189 non-null    int64
 11  FGA                189 non-null    int64
 12  FG_PCT             189 non-null    float64
 13  FG3M               189 non-null    int64
 14  FG3A               189 non-null    int64
 15  FG3_PCT            189 non-null    float64
 16  FTM                189 non-null    int64
 17  FTA                189 non-null    int64
 18  FT_PCT             188 non-null    float64
 19  OREB               189 non-null    int64
 20  DREB               189 non-null    int64
 21  REB                189 non-null    int64
 22  AST                189 non-null    int64
 23  STL                189 non-null    int64
 24  BLK                189 non-null    int64
 25  TOV                189 non-null    int64
 26  PF                 189 non-null    int64
 27  PLUS_MINUS         189 non-null    float64
 28  HOME               189 non-null    bool
dtypes: bool(1), float64(4), int64(17), object(7)
memory usage: 43.0+ KB

In [11]:
# Transformando IDs em numéricos
jogos['SEASON'] = pd.to_numeric(jogos['SEASON'])
jogos['GAME_ID'] = pd.to_numeric(jogos['GAME_ID'])

In [12]:
# Conferindo
jogos.tail().T

,204,205,206,207,208
SEASON,2018,2018,2018,2018,2018
TEAM_ID,1610612742,1610612742,1610612742,1610612742,1610612742
TEAM_ABBREVIATION,DAL,DAL,DAL,DAL,DAL
TEAM_NAME,Dallas Mavericks,Dallas Mavericks,Dallas Mavericks,Dallas Mavericks,Dallas Mavericks
GAME_ID,21800069,21800052,21800044,21800032,21800013
GAME_DATE,2018-10-26,2018-10-24,2018-10-22,2018-10-20,2018-10-17
MATCHUP,DAL @ TOR,DAL @ ATL,DAL vs. CHI,DAL vs. MIN,DAL @ PHX
WL,L,L,W,W,L
MIN,35,34,36,36,32
PTS,22,21,19,26,10
FGM,7,7,7,8,5
FGA,14,18,14,16,16
FG_PCT,0.5,0.389,0.5,0.5,0.313
FG3M,4,2,3,4,0
FG3A,6,9,8,9,5
FG3_PCT,0.667,0.222,0.375,0.444,0.0
FTM,4,5,2,6,0
FTA,4,8,2,9,2
FT_PCT,1.0,0.625,1.0,0.667,0.0
OREB,1,0,0,1,2
DREB,4,9,3,5,6
REB,5,9,3,6,8
AST,4,2,6,3,4
STL,0,1,1,2,0
BLK,0,1,0,1,0
TOV,3,3,3,6,4
PF,1,2,3,3,3
PLUS_MINUS,0.0,-2.4,1.0,0.8,-3.6
HOME,False,False,True,True,False

In [13]:
arquivo = nome+'.csv'
jogos.to_csv(arquivo, index=False)

In [14]:
from nba_api.stats.endpoints import playercareerstats
# Anthony Davis
career = playercareerstats.PlayerCareerStats(player_id=jogador['id']).get_data_frames()[0]
career.head().T

                            0           1           2
PLAYER_ID             1629029     1629029     1629029
SEASON_ID             2018-19     2019-20     2020-21
LEAGUE_ID                  00          00          00
TEAM_ID            1610612742  1610612742  1610612742
TEAM_ABBREVIATION         DAL         DAL         DAL
PLAYER_AGE               20.0        21.0        22.0
GP                         72          61          56
GS                         72          61          56
MIN                    2318.0      2047.0      1964.0
FGM                       506         581         567
FGA                      1186        1255        1169
FG_PCT                  0.427       0.463       0.485
FG3M                      168         171         169
FG3A                      514         541         471
FG3_PCT                 0.327       0.316       0.359
FTM                       346         426         297
FTA                       485         562         407
FT_PCT                  0.713       0.758        0.73
OREB                       86          78          45
DREB                      477         495         400
REB                       563         573         445
AST                       429         538         489
STL                        77          62          56
BLK                        25          14          34
TOV                       247         260         243
PF                        137         153         130
PTS                      1526        1759        1600

In [15]:
arquivo = nome+' Career.csv'
career.to_csv(arquivo, index=False)

In [16]:
career.shape

(3, 27)